// Part O — Multi-industry demo seeds: Semiconductor and Warehouse & Logistics.
// Same design rule as lib/demo-seed.ts (which is untouched): everything goes
// through the SAME code paths a real user exercises — every SPC/OEE/YIELD
// point runs its real rules function on entry, every defect runs runNcRules
// (recurrence → auto-drafted CAPA), FMEA items go through the real
// upsertFmeaItem action, the playbook is advanced step-by-step through the
// real guided/advance actions, and nothing is written into `computed`,
// `alerts`, `decisions`, or `capas` by hand. The SPC series below are
// verified in scripts/verify-calcs.ts through the real lib/spc.ts functions:
// they stay in control for the stable prefix, then trigger the documented
// Western Electric rules, and (semiconductor) drop rolling Cpk below the
// strict 1.67 industry threshold on the final points.

import { db, t } from "@/db";
import { and, eq, like } from "drizzle-orm";
import { runSpcRules, runNcRules, runOeeRules } from "@/lib/rules";
import { runYieldRules } from "@/lib/yield";
import type { SeedDeps } from "@/lib/demo-seed";

const fd = (obj: Record<string, string>) => {
  const f = new FormData();
  for (const [k, v] of Object.entries(obj)) f.set(k, v);
  return f;
};
const daysAgo = (n: number, hour = 10, minute = 30) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d;
};

// Etch CD (nm), nominal 120.0, LSL 119.5 / USL 120.5, Cpk threshold 1.67
// (strict electronics/semi default). First 16 points stable; then a chamber-
// seasoning downward drift: WE1+WE2 fire at point 19, WE3 joins at 20, WE4 at
// 24, and rolling Cpk ends at ≈1.61 < 1.67 → CPK_LOW fires from runSpcRules.
export const SEMI_SPC_VALUES = [
  120.05, 119.92, 120.10, 119.98, 120.03, 119.95, 120.08, 120.00,
  119.94, 120.06, 120.01, 119.97, 120.04, 119.99, 120.02, 119.96,
  119.85, 119.78, 119.72, 119.66, 119.60, 119.52, 119.42, 119.22,
];

// Pick time per order line (sec), I-MR, no spec limits. First 13 points
// stable; then peak-season ramp with untrained temps: WE2 fires at point 16,
// WE1 at 17, WE3 from 18 — verified through the real lib/spc.ts.
export const LOGISTICS_SPC_VALUES = [
  42.1, 40.8, 41.9, 41.2, 40.5, 41.6, 40.9, 41.4, 41.0, 41.8, 40.7, 41.3, 41.1,
  42.4, 43.0, 43.6, 44.3, 45.0, 45.9, 47.2,
];

async function ensureWorkspace(userId: string, name: string, industry: string, processType: string) {
  const mine = await db.select({ ws: t.workspaces }).from(t.memberships)
    .innerJoin(t.workspaces, eq(t.workspaces.id, t.memberships.workspaceId))
    .where(eq(t.memberships.userId, userId));
  let ws = mine.map(r => r.ws).find(w => w.name === name && w.industry === industry);
  if (!ws) {
    [ws] = await db.insert(t.workspaces).values({ name, industry, processType }).returning();
    await db.insert(t.memberships).values({ userId, workspaceId: ws.id, role: "owner" });
  }
  return ws;
}

async function freshProject(workspaceId: string, baseName: string, description: string) {
  const clashes = await db.select({ name: t.projects.name }).from(t.projects)
    .where(and(eq(t.projects.workspaceId, workspaceId), like(t.projects.name, `${baseName}%`)));
  const name = clashes.length === 0 ? baseName : `${baseName} (${clashes.length + 1})`;
  const [project] = await db.insert(t.projects).values({ workspaceId, name, description }).returning();
  return project;
}

// ---- Semiconductor: etch CD drift on a plasma etcher -------------------------
export async function seedSemiconductorDemo(userId: string, deps: SeedDeps): Promise<{ projectId: string }> {
  const ws = await ensureWorkspace(userId, "Demo — Semiconductor", "electronics", "batch");
  const project = await freshProject(ws.id, "Demo: Etch CD Drift",
    "Seeded example — critical-dimension drift on a plasma etcher, with wafer-sort yield stages. Every alert, CAPA and decision was generated by the app's own rules, not inserted by hand.");

  // SPC stream (I-MR): one CD measurement per lot, backdated across ~3.5 weeks.
  const [spc] = await db.insert(t.streams).values({
    projectId: project.id, name: "Etch CD — Chamber B", type: "SPC_IMR",
    unit: "nm", subgroupSize: 1, specLow: 119.5, specHigh: 120.5, cpkThreshold: 1.67,
  }).returning();
  for (let i = 0; i < SEMI_SPC_VALUES.length; i++) {
    const [pt] = await db.insert(t.dataPoints).values({
      streamId: spc.id, ts: daysAgo(SEMI_SPC_VALUES.length - i),
      payload: { values: [SEMI_SPC_VALUES[i]] },
    }).returning();
    await runSpcRules(spc.id, pt.id); // WE flags + CPK_LOW fire here, for real
  }

  // Part D in action: two YIELD stages (litho, etch) — the etch stage runs
  // 3 consecutive days below its 92% threshold, so YIELD_BELOW_THRESHOLD
  // fires from the real runYieldRules; RTY multiplies across the stages.
  const stages: { name: string; threshold: number; entries: { started: number; passed: number; scrap: { reason: string; qty: number }[] }[] }[] = [
    {
      name: "Stage 1 — Litho", threshold: 0.95, entries: [
        { started: 400, passed: 391, scrap: [{ reason: "Overlay misalignment", qty: 6 }, { reason: "Resist defect", qty: 3 }] },
        { started: 380, passed: 372, scrap: [{ reason: "Overlay misalignment", qty: 5 }, { reason: "Particle", qty: 3 }] },
        { started: 410, passed: 402, scrap: [{ reason: "Resist defect", qty: 5 }, { reason: "Overlay misalignment", qty: 3 }] },
        { started: 395, passed: 388, scrap: [{ reason: "Overlay misalignment", qty: 4 }, { reason: "Particle", qty: 3 }] },
      ],
    },
    {
      name: "Stage 2 — Etch", threshold: 0.92, entries: [
        { started: 391, passed: 366, scrap: [{ reason: "CD out of spec", qty: 17 }, { reason: "Etch residue", qty: 8 }] },   // 93.6%
        { started: 372, passed: 341, scrap: [{ reason: "CD out of spec", qty: 23 }, { reason: "Etch residue", qty: 8 }] },   // 91.7% ↓
        { started: 402, passed: 365, scrap: [{ reason: "CD out of spec", qty: 29 }, { reason: "Micro-loading", qty: 8 }] },  // 90.8% ↓
        { started: 388, passed: 349, scrap: [{ reason: "CD out of spec", qty: 31 }, { reason: "Etch residue", qty: 8 }] },   // 89.9% ↓ → alert
      ],
    },
  ];
  for (const st of stages) {
    const [ys] = await db.insert(t.streams).values({
      projectId: project.id, name: st.name, type: "YIELD", subgroupSize: 1, target: st.threshold,
    }).returning();
    for (let i = 0; i < st.entries.length; i++) {
      const [pt] = await db.insert(t.dataPoints).values({
        streamId: ys.id, ts: daysAgo(st.entries.length - i, 17, 0), payload: st.entries[i],
      }).returning();
      await runYieldRules(ys.id, pt.id); // FPY computed + 3-consecutive rule, for real
    }
  }

  // Deviations: CD-OOS repeats 3× in the window → real recurrence rule drafts a CAPA
  // (electronics threshold = 3, per lib/terminology defaults).
  const DEFECTS = [
    { day: 16, code: "CD-OOS", area: "Etch Chamber B", qty: 12, severity: "major", description: "CD 119.6 nm at lot sort — low edge of spec" },
    { day: 12, code: "PARTICLE", area: "Litho track 1", qty: 3, severity: "minor", description: "Particle count spike after PM" },
    { day: 10, code: "CD-OOS", area: "Etch Chamber B", qty: 18, severity: "major", description: "CD trending low — chamber seasoning suspected" },
    { day: 6, code: "RESIST-DEFECT", area: "Litho track 1", qty: 4, severity: "minor", description: "Resist bubble on wafer edge" },
    { day: 3, code: "CD-OOS", area: "Etch Chamber B", qty: 24, severity: "critical", description: "CD 119.3 nm below LSL — lot held" },
  ];
  for (const d of DEFECTS) {
    const [nc] = await db.insert(t.nonConformances).values({
      projectId: project.id, date: daysAgo(d.day, 14, 0),
      defectCode: d.code, processArea: d.area, qty: d.qty, severity: d.severity, description: d.description,
    }).returning();
    await runNcRules(project.id, nc.id, "electronics");
  }

  // FMEA through the real action (server-side RPN + threshold alert at 80: strict default).
  const [fmea] = await db.insert(t.fmeas).values({
    projectId: project.id, name: "Etch process PFMEA", type: "PFMEA", rpnAction: 80,
  }).returning();
  const items = [
    { processStep: "OP30 — Plasma etch", failureMode: "CD below LSL", effect: "Device leakage; die fails wafer sort", cause: "Chamber seasoning shifts etch rate between cleans", severity: "8", occurrence: "5", detection: "3", recommendedAction: "Add CD feed-forward compensation from litho metrology; shorten clean interval", actionStatus: "open", linkedDefectCode: "CD-OOS" }, // RPN 120
    { processStep: "OP10 — Litho expose", failureMode: "Overlay misalignment", effect: "Short/open at metal layer", cause: "Stage calibration drift", severity: "7", occurrence: "3", detection: "3", recommendedAction: "Daily overlay verification wafer", actionStatus: "open", linkedDefectCode: "" }, // RPN 63
    { processStep: "OP30 — Plasma etch", failureMode: "Etch residue remains", effect: "Contact resistance high", cause: "Polymer buildup at low chamber temp", severity: "6", occurrence: "3", detection: "4", recommendedAction: "Temperature interlock before lot start", actionStatus: "none", linkedDefectCode: "" }, // RPN 72
  ];
  for (const it of items) {
    await deps.upsertFmeaItem(null, fd({ projectId: project.id, fmeaId: fmea.id, id: "", ...it }));
  }

  // Completed playbook run through the real advance action (decision-gate rows logged for real).
  const [run] = await db.insert(t.playbookRuns).values({ projectId: project.id, playbookKey: "reduce_defects" }).returning();
  const steps: Record<string, string>[] = [
    { process: "Plasma etch — Chamber B, all shifts", problem: "Wafer-sort CD-related yield loss doubled since the chamber wet clean in WW24: etch-stage FPY now ~90% vs 96% baseline, concentrated on Chamber B.", metric: "Etch-stage first-pass yield % (CD-related scrap)" },
    { baseline_days: "20" },
    { gate_choice: "Fix process capability (re-center or reduce variation)", gate_rationale: "The control chart shows a sustained downward CD drift (WE1–WE4 all fired) and rolling Cpk fell to 1.61 against the 1.67 threshold — this is the process drifting, not isolated events.", gate_decidedBy: "Etch module engineering" },
    { gate_choice: "Process change", gate_rationale: "Root cause is seasoning-driven etch-rate shift between cleans — implement CD feed-forward compensation and a shorter clean interval rather than chasing individual lots.", gate_decidedBy: "Etch module engineering" },
    { control_plan: "CD logged per lot on the I-MR chart; SPC alert holds the chamber pending etch-rate check; yield stages tracked daily with the 92% threshold; FMEA occurrence re-scored after 30 days." },
  ];
  for (const step of steps) await deps.advancePlaybook(null, fd({ projectId: project.id, runId: run.id, ...step }));

  // Resolve the earliest flagged SPC entries through the real action (old news the team handled).
  const spcAlerts = await db.select().from(t.alerts).where(and(
    eq(t.alerts.projectId, project.id), eq(t.alerts.sourceType, "SPC"))).orderBy(t.alerts.createdAt);
  const firstEntry = spcAlerts[0]?.sourceId;
  for (const a of spcAlerts.filter(a => a.sourceId === firstEntry)) {
    await deps.setAlertStatus(null, fd({ projectId: project.id, id: a.id, status: "resolved" }));
  }
  return { projectId: project.id };
}

// ---- Warehouse & logistics: pick-time creep during peak-season ramp ----------
export async function seedLogisticsDemo(userId: string, deps: SeedDeps): Promise<{ projectId: string }> {
  const ws = await ensureWorkspace(userId, "Demo — Logistics", "warehouse_logistics", "service");
  const project = await freshProject(ws.id, "Demo: Pick Line Ramp",
    "Seeded example — pick-time creep and error spike during a peak-season ramp with new associates. Every alert, CAPA and decision was generated by the app's own rules, not inserted by hand.");

  // SPC I-MR: average pick time per order line, one sample per day.
  const [spc] = await db.insert(t.streams).values({
    projectId: project.id, name: "Pick time per line — Zone C", type: "SPC_IMR",
    unit: "sec", subgroupSize: 1, cpkThreshold: 1.33,
  }).returning();
  for (let i = 0; i < LOGISTICS_SPC_VALUES.length; i++) {
    const [pt] = await db.insert(t.dataPoints).values({
      streamId: spc.id, ts: daysAgo(LOGISTICS_SPC_VALUES.length - i),
      payload: { values: [LOGISTICS_SPC_VALUES[i]] },
    }).returning();
    await runSpcRules(spc.id, pt.id);
  }

  // OEE on the pack line: 3 consecutive days below the 0.75 logistics target →
  // OEE_BELOW_TARGET fires from the real runOeeRules.
  const [oee] = await db.insert(t.streams).values({
    projectId: project.id, name: "Pack line 2 — daily OEE", type: "OEE", subgroupSize: 1, target: 0.75,
  }).returning();
  const OEE_ENTRIES = [
    { planned: 480, runtime: 440, idealCycle: 0.25, total: 1650, good: 1622 }, // ≈ 92.2%
    { planned: 480, runtime: 430, idealCycle: 0.25, total: 1290, good: 1252 }, // ≈ 66.3% ↓
    { planned: 480, runtime: 415, idealCycle: 0.25, total: 1245, good: 1201 }, // ≈ 62.6% ↓
    { planned: 480, runtime: 420, idealCycle: 0.25, total: 1260, good: 1210 }, // ≈ 63.0% ↓ → alert
  ];
  for (let i = 0; i < OEE_ENTRIES.length; i++) {
    const [pt] = await db.insert(t.dataPoints).values({
      streamId: oee.id, ts: daysAgo(OEE_ENTRIES.length - i, 18, 0), payload: OEE_ENTRIES[i],
    }).returning();
    await runOeeRules(oee.id, pt.id);
  }

  // Errors: WRONG-ITEM repeats 3× in Zone C within the window → auto-drafted CAPA.
  const DEFECTS = [
    { day: 14, code: "WRONG-ITEM", area: "Pick Zone C", qty: 3, severity: "major", description: "Look-alike SKUs in adjacent bins — new associate" },
    { day: 11, code: "SHORT-PICK", area: "Pick Zone A", qty: 2, severity: "minor", description: "Bin count off after replen" },
    { day: 8, code: "WRONG-ITEM", area: "Pick Zone C", qty: 4, severity: "major", description: "Same bin pair as last week" },
    { day: 5, code: "LABEL-DAMAGE", area: "Pack line 2", qty: 2, severity: "minor", description: "Printer head streaking" },
    { day: 2, code: "WRONG-ITEM", area: "Pick Zone C", qty: 5, severity: "major", description: "Third recurrence — customer complaint received" },
  ];
  for (const d of DEFECTS) {
    const [nc] = await db.insert(t.nonConformances).values({
      projectId: project.id, date: daysAgo(d.day, 14, 0),
      defectCode: d.code, processArea: d.area, qty: d.qty, severity: d.severity, description: d.description,
    }).returning();
    await runNcRules(project.id, nc.id, "warehouse_logistics");
  }

  // FMEA through the real action.
  const [fmea] = await db.insert(t.fmeas).values({
    projectId: project.id, name: "Pick-pack PFMEA", type: "PFMEA", rpnAction: 100,
  }).returning();
  const items = [
    { processStep: "Pick — Zone C", failureMode: "Wrong item picked", effect: "Customer receives wrong product; return + reship cost", cause: "Look-alike SKUs slotted in adjacent bins", severity: "6", occurrence: "6", detection: "3", recommendedAction: "Re-slot look-alike pairs apart; add scan-verify at pick", actionStatus: "open", linkedDefectCode: "WRONG-ITEM" }, // RPN 108
    { processStep: "Pack line 2", failureMode: "Label unreadable", effect: "Carrier mis-sort; late delivery", cause: "Worn printer head, no PM schedule", severity: "5", occurrence: "3", detection: "2", recommendedAction: "Add printer PM to recurring tasks", actionStatus: "none", linkedDefectCode: "LABEL-DAMAGE" }, // RPN 30
    { processStep: "Replenishment", failureMode: "Bin short after replen", effect: "Short picks; order splits", cause: "Replen confirmed before physically complete", severity: "4", occurrence: "4", detection: "4", recommendedAction: "Confirm-on-scan at bin, not at cart", actionStatus: "none", linkedDefectCode: "SHORT-PICK" }, // RPN 64
  ];
  for (const it of items) {
    await deps.upsertFmeaItem(null, fd({ projectId: project.id, fmeaId: fmea.id, id: "", ...it }));
  }

  // Completed playbook run through the real advance action.
  const [run] = await db.insert(t.playbookRuns).values({ projectId: project.id, playbookKey: "reduce_defects" }).returning();
  const steps: Record<string, string>[] = [
    { process: "Pick Zone C + Pack line 2, day shift", problem: "Since the peak-season ramp started (8 new associates), wrong-item errors tripled and average pick time in Zone C climbed from ~41 s to 47 s per line.", metric: "Wrong-item errors per 1,000 order lines" },
    { baseline_days: "13" },
    { gate_choice: "Attack the #1 defect code", gate_rationale: "Pareto shows WRONG-ITEM dominates and every occurrence is the same look-alike bin pair in Zone C — a specific, findable cause. The pick-time chart confirms the ramp is when it started (WE rule violations from day 17).", gate_decidedBy: "Outbound ops team" },
    { gate_choice: "Error-proofing (poka-yoke)", gate_rationale: "Scan-verify at pick makes the wrong-item mistake physically hard to commit regardless of associate experience — more durable than training alone during a ramp.", gate_decidedBy: "Outbound ops team" },
    { control_plan: "Pick time logged daily on the I-MR chart; wrong-item errors logged per occurrence with zone; OEE on pack line 2 tracked against the 75% target; scan-verify compliance audited weekly as a recurring task." },
  ];
  for (const step of steps) await deps.advancePlaybook(null, fd({ projectId: project.id, runId: run.id, ...step }));

  return { projectId: project.id };
}
